"""Render every figure to committed files that the docs site and PPT both use.

Local entrypoint (needs the real Python env + experiment data). Writes SVG
(vector, drops into PowerPoint and mystmd) plus a PNG@2x fallback for Office
templates that choke on SVG.

Usage:
    python -m ic1.reporting.build_figures                 # all figures
    python -m ic1.reporting.build_figures --formats svg   # svg only
"""

from __future__ import annotations

import argparse
from pathlib import Path

from matplotlib.figure import Figure

from ic1.reporting.loaders import (
    inout_agreement_by_set,
    inout_coder_counts,
    inout_coder_f1,
    inout_coderset_composition,
    inout_cycle_spans,
    inout_overall_agreement,
    inout_pairwise_kappa,
    inout_screening_raster,
    inout_unanimous_dispersion,
    load_inout_annotations,
    load_inout_comparison,
    load_inout_model_costs,
    load_inout_prompt_churn,
    load_inout_prompts,
    load_inout_runs,
    load_inout_splits,
    load_inout_test_metrics,
    load_taxonomy_concept_tree,
    load_taxonomy_cost_performance,
    load_taxonomy_level_scores,
    load_taxonomy_prompt_churn,
    load_taxonomy_runs,
    load_taxonomy_scheme_scores,
)
from ic1.reporting.plots import (
    plot_agreement_by_set,
    plot_coder_counts,
    plot_coder_model_pr,
    plot_coder_pr,
    plot_coderset_composition,
    plot_comparison,
    plot_cost_performance,
    plot_data_splits,
    plot_iteration_timeline,
    plot_pairwise_kappa,
    plot_scheme_scores,
    plot_screening_raster,
    plot_taxonomy_cost_performance,
    plot_taxonomy_level_scores,
    plot_unanimous_funnel,
)
from ic1.reporting.style import MODE_COLORS, apply_style
from ic1.reporting.tables import (
    annotation_agreement_markdown,
    annotation_f1_markdown,
    comparison_markdown,
    metrics_markdown,
    prompts_markdown,
    taxonomy_drilldown_html,
)

_REPO_ROOT = Path(__file__).resolve().parents[2]
FIGURES_DIR = _REPO_ROOT / "docs" / "figures"
TABLES_DIR = _REPO_ROOT / "docs" / "tables"


def _write_table(md: str, name: str) -> None:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    path = TABLES_DIR / f"{name}.md"
    path.write_text(
        "<!-- generated by `python -m ic1.reporting.build_figures` — do not edit -->\n\n"
        + md
    )
    print(f"  wrote {path.relative_to(_REPO_ROOT)}")


def _save(fig: Figure, domain: str, name: str, formats: tuple[str, ...]) -> None:
    out_dir = FIGURES_DIR / domain
    out_dir.mkdir(parents=True, exist_ok=True)
    for fmt in formats:
        path = out_dir / f"{name}.{fmt}"
        # Drop the SVG creation-date metadata so identical data -> identical bytes
        # (no timestamp churn in git). PNGs carry no timestamp by default.
        metadata = {"Date": None} if fmt == "svg" else None
        fig.savefig(path, format=fmt, metadata=metadata)
        print(f"  wrote {path.relative_to(_REPO_ROOT)}")


def build_taxonomy(formats: tuple[str, ...]) -> None:
    runs = load_taxonomy_runs()
    churn = load_taxonomy_prompt_churn()
    print(f"taxonomy: {len(runs)} completed runs")
    _save(
        plot_iteration_timeline(runs, churn=churn),
        "taxonomy", "iteration_timeline", formats,
    )
    _save(
        plot_taxonomy_cost_performance(load_taxonomy_cost_performance()),
        "taxonomy", "cost_performance", formats,
    )

    chosen = runs.loc[runs.micro.idxmax(), "run"]
    print(f"  per-scheme scores for {chosen}")
    scheme_scores = load_taxonomy_scheme_scores(chosen)
    _save(
        plot_scheme_scores(scheme_scores),
        "taxonomy", "scheme_scores", formats,
    )
    _save(
        plot_taxonomy_level_scores(load_taxonomy_level_scores(chosen), scheme_scores),
        "taxonomy", "level_scores", formats,
    )
    _write_table(
        taxonomy_drilldown_html(load_taxonomy_concept_tree(chosen)),
        "taxonomy_drilldown",
    )


def build_inout(formats: tuple[str, ...]) -> None:
    splits = load_inout_splits()
    print(
        f"inout splits: train {splits['train']:,} / val {splits['validation']:,} "
        f"/ test {splits['test']:,} (LLM dev {splits['llm_dev']})"
    )
    _save(plot_data_splits(splits), "inout", "data_splits", formats)

    runs = load_inout_runs()
    churn = load_inout_prompt_churn()
    print(f"inout: {runs.run.nunique()} prompt states ({len(runs)} state x mode rows)")
    _save(
        plot_iteration_timeline(
            runs, churn=churn,
            metrics=("precision", "recall"),
            color_map=MODE_COLORS, color_title="Operating mode",
            spans=inout_cycle_spans(runs), churn_yscale="linear",
            title="Prompt-engineering iterations — in/out relevance screen",
        ),
        "inout", "iteration_timeline", formats,
    )
    _save(
        plot_cost_performance(load_inout_model_costs()),
        "inout", "cost_performance", formats,
    )
    test = load_inout_test_metrics()
    if not test.empty:
        _write_table(metrics_markdown(test), "inout_test_metrics")
    try:
        comp = load_inout_comparison()
        _save(plot_comparison(comp), "inout", "comparison", formats)
        _write_table(comparison_markdown(comp), "inout_comparison")
    except (FileNotFoundError, ValueError) as e:
        print(f"  skipping comparison: {e}")
    try:
        _write_table(prompts_markdown(load_inout_prompts()), "inout_prompts")
    except (FileNotFoundError, KeyError) as e:
        print(f"  skipping prompts: {e}")


def build_inout_annotation(formats: tuple[str, ...]) -> None:
    """Human-annotation figures/tables: counts, agreement, coder F1."""
    ann = load_inout_annotations()
    counts = inout_coder_counts(ann)
    comp = inout_coderset_composition(ann)
    overall = inout_overall_agreement(ann)
    by_set = inout_agreement_by_set(ann)
    f1 = inout_coder_f1(ann)
    print(
        f"inout annotation: {int(counts.n.sum()):,} coder annotations over "
        f"{int(comp.n_items.sum()):,} docs, {len(comp)} coder-sets; "
        f"overall Fleiss κ={overall['fleiss']:.2f}"
    )
    _save(plot_coder_counts(counts), "inout", "annotation_coder_counts", formats)
    _save(plot_coderset_composition(comp), "inout", "annotation_composition", formats)
    _save(plot_screening_raster(inout_screening_raster(ann)),
          "inout", "annotation_raster", formats)
    _save(plot_agreement_by_set(by_set, overall), "inout", "annotation_agreement", formats)
    _save(plot_pairwise_kappa(inout_pairwise_kappa(ann)),
          "inout", "annotation_pairwise_kappa", formats)
    _save(plot_unanimous_funnel(inout_unanimous_dispersion(ann)),
          "inout", "annotation_unanimous_funnel", formats)
    _save(plot_coder_pr(f1), "inout", "annotation_coder_pr", formats)
    try:
        _save(plot_coder_model_pr(f1, load_inout_comparison()),
              "inout", "annotation_coder_model_pr", formats)
    except (FileNotFoundError, ValueError) as e:
        print(f"  skipping coder-vs-model PR: {e}")
    _write_table(annotation_agreement_markdown(by_set, overall), "inout_annotation_agreement")
    _write_table(annotation_f1_markdown(f1), "inout_annotation_f1")

    # Private real-name renders of the identity-revealing figures. Written under
    # a *_private.* filename, which .gitignore keeps out of the repo.
    priv_csv = _REPO_ROOT / "data" / "private" / "exports" / "inout.csv"
    if priv_csv.exists():
        pann = load_inout_annotations(priv_csv)
        _save(plot_screening_raster(inout_screening_raster(pann)),
              "inout", "annotation_raster_private", formats)
        _save(plot_unanimous_funnel(inout_unanimous_dispersion(pann)),
              "inout", "annotation_unanimous_funnel_private", formats)
        _save(plot_coder_pr(inout_coder_f1(pann), label="name"),
              "inout", "annotation_coder_pr_private", formats)
        print("  (rendered private real-name versions — gitignored)")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--domain", choices=["taxonomy", "inout", "all"], default="all")
    ap.add_argument("--formats", nargs="+", default=["svg", "png"])
    args = ap.parse_args()

    apply_style()
    formats = tuple(args.formats)
    if args.domain in ("taxonomy", "all"):
        build_taxonomy(formats)
    if args.domain in ("inout", "all"):
        build_inout(formats)
        build_inout_annotation(formats)


if __name__ == "__main__":
    main()
