project:
  created_at: '2026-08-03T11:22:25.224362Z'
  evaluation_strategy: dev_val_test
  gold_standard_data_format: generic_csv
  gold_standard_data_path: ../../../../data/private/exports/inout_deet.csv
  name: IC1-inout
  pdf_dir: null
